dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-02/run.sh | bash
notifications:
  slack:
    rooms:
      secure: W2OVExG0W3Xdzrw/Waqbj7lYh3iJsiwcsv281JCoBIRRYXfMB/L/oawJ1vb3VJE4eaEj4CUrLpVo7XReENny9fRtRwO1g4HBY+BSPdgrEkhfupi8cP7aYaL4vGperlolAWwxUBFkUvHNu8Y3vvI1qZvzD0UgWC49WLPDHlMgIelt62lIVYcv2FBDEm92cV06KnS1Z6AszbiLtOiGoWnyAJ0BGRKSlvIRa64WNgukesTGAPYtryqJ/KGxrWWxk7ifuqbQ5YMjDauoNzGvpt7Xy0kRW+hdzIBiUQ9Kxegw2l+ydz1g3AF+mV0fcX9Pm4q2sW+dyOyWywy2lrLNTQRvepPYkCMZmSDD0M9ul6GEhpg2sQuJpdMoYOqJZjB0n5jQpY23XGlkhG//aXPHO3lMxsl4Pf+uCe5/pucqISiLUECMJ3Ork3R9OEB52VVhyoJmISkKBN+1SmKgL1YZtLhcKilNnyDFL46693zb7A6TRyHqfOQrrspsPfvurQRpChEY8OmYZ2BQJ0kucjtZg9hHZeKPBWREsx5bdjQcgSWNrhfUIBfyp5sL11L1x5An4Qr945wGnwrlHEBTqha92cMbhnHXLaE3SClTMc+3TEF86ylqI3z8ANfAmmiWmXiZ83dzDAN06y1BjyOni+Py+tMz5cyDD5FV53dux1OHCGcCy2Y=
