version: "3.3"
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - comment_db
          - post_db
  ui:
    image: ${USER_NAME}/ui
    ports:
      - 9292:9292/tcp
    networks:
      - front_net

  post:
    image: ${USER_NAME}/post
    networks:
      - back_net
      - front_net

  comment:
    image: ${USER_NAME}/comment
    networks:
      - back_net
      - front_net

volumes:
  post_db:

networks:
  back_net:
  front_net:
