---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: post
  labels:
    app: reddit
    component: post
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reddit
  template:
    metadata:
      name: post
      labels:
        app: reddit
        component: post
    spec:
      containers:
        - image: bas27/post
          name: post
          env:
          - name: POST_DATABASE_HOST
            value: post-db
